var annotated_dup =
[
    [ "s_amb", "structs__amb.html", "structs__amb" ],
    [ "s_area", "structs__area.html", "structs__area" ],
    [ "s_bhask", "structs__bhask.html", "structs__bhask" ],
    [ "s_camera", "structs__camera.html", "structs__camera" ],
    [ "s_canvas", "structs__canvas.html", "structs__canvas" ],
    [ "s_comps", "structs__comps.html", "structs__comps" ],
    [ "s_cone", "structs__cone.html", "structs__cone" ],
    [ "s_context", "structs__context.html", "structs__context" ],
    [ "s_cube", "structs__cube.html", "structs__cube" ],
    [ "s_cylinder", "structs__cylinder.html", "structs__cylinder" ],
    [ "s_image", "structs__image.html", "structs__image" ],
    [ "s_intersection", "structs__intersection.html", "structs__intersection" ],
    [ "s_key_map", "structs__key__map.html", null ],
    [ "s_light", "structs__light.html", "structs__light" ],
    [ "s_lighting", "structs__lighting.html", "structs__lighting" ],
    [ "s_list", "structs__list.html", null ],
    [ "s_material", "structs__material.html", "structs__material" ],
    [ "s_matrix", "structs__matrix.html", "structs__matrix" ],
    [ "s_pattern", "structs__pattern.html", "structs__pattern" ],
    [ "s_plane", "structs__plane.html", "structs__plane" ],
    [ "s_ray", "structs__ray.html", "structs__ray" ],
    [ "s_row1", "structs__row1.html", null ],
    [ "s_row2", "structs__row2.html", null ],
    [ "s_row3", "structs__row3.html", null ],
    [ "s_row4", "structs__row4.html", null ],
    [ "s_row5", "structs__row5.html", null ],
    [ "s_row6", "structs__row6.html", null ],
    [ "s_scene", "structs__scene.html", "structs__scene" ],
    [ "s_shapes", "structs__shapes.html", "structs__shapes" ],
    [ "s_sphere", "structs__sphere.html", "structs__sphere" ],
    [ "s_triangle", "structs__triangle.html", "structs__triangle" ],
    [ "s_vec3", "structs__vec3.html", "structs__vec3" ],
    [ "s_world", "structs__world.html", "structs__world" ]
];